SELECT DEPT_CODE, JOB_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY CUBE(DEPT_CODE, JOB_CODE);
-- 위 아래 같은 결과를 나오게 하기 위해서는 CUBE(C1, C2) = ROLLUP(C1, C2)+ROLLUP(C2)
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY ROLLUP(DEPT_CODE, JOB_CODE)
UNION ALL
SELECT '', JOB_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY ROLLUP(JOB_CODE) ORDER BY 1;


SELECT DEPT_CODE, JOB_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY CUBE(DEPT_CODE, JOB_CODE);
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY),
        CASE
        -- GROUPING(C1) : C1의 집계부분인지 0,1로 확인 됨.
        -- 0 : 해당 컬럼으로 GROUPING 된 안된상태. = C1 전체부분
        -- 1 : 해당하는 칼럼으로 GROUPING 된 상태.
        WHEN GROUPING(DEPT_CODE) = 0 AND GROUPING(JOB_CODE) = 1 THEN '부 합계'
        WHEN GROUPING(DEPT_CODE) = 1 AND GROUPING(JOB_CODE) = 0 THEN '직'
        WHEN GROUPING(DEPT_CODE) = 1 AND GROUPING(JOB_CODE) = 1 THEN '총 합계'
        ELSE '그룹별 합계'
        END AS 구분
    FROM EMPLOYEE
    GROUP BY CUBE(DEPT_CODE, JOB_CODE)
    ORDER BY 1;
    
-- GROUPING SETS : GROUP BY 한 결과물을 UNION함
SELECT DEPT_CODE, JOB_CODE, MANAGER_ID, FLOOR(AVG(SALARY)) FROM EMPLOYEE
    GROUP BY GROUPING SETS((DEPT_CODE, JOB, MANGET)ID),(DEPT_CODE, MANAGER_ID), (JOB_CODE, MANAGER_ID));
    
    
SELECT EMP_ID, EMP_NAME, SALARY,
RANK() OVER(ORDER BY SALARY DESC) 급여순위
FROM EMPLOYEE;

SELECT RANK(2300000) 
WITHIN GROUP (ORDER BY SALARY DESC) AS 순위
FROM EMPLOYEE;

SELECT EMP_NAME, EMP_ID, SALARY,
RANK() OVER (ORDER BY SALARY DESC) "순위1",
DENSE_RANK() OVER (ORDER BY SALARY DESC) "순위2",
DENSE_RANK() OVER (PARTITION BY EMP_ID ORDER BY SALARY DESC) "순위3" -- 그룹 안에서의 순위
FROM EMPLOYEE
ORDER BY 2 asc;

SELECT *
FROM (SELECT EMP_NAME, SALARY,
        RANK() OVER (ORDER BY SALARY DESC) 순위
        FROM EMPLOYEE)
WHERE 순위 <= 5; -- 상위 5개의 정보 조회
