CREATE OR REPLACE PROCEDURE PRO_EMPLOYEE_ARG_TEST
    ( ARG_EMPID IN EMPLOYEE.EMP_ID%TYPE
     ,ARG_ENAME OUT EMPLOYEE.EMP_NAME%TYPE
     ,ARG_SAL OUT EMPLOYEE.SALARY%TYPE
     ,ARG_EMAIL OUT EMPLOYEE.EMAIL%TYPE
     )
IS
BEGIN
    SELECT EMP_NAME, SALARY, EMAIL
    INTO ARG_ENAME, ARG_SAL, ARG_EMAIL
    FROM EMPLOYEE
    WHERE EMP_ID = ARG_EMPID;
    DBMS_OUTPUT.PUT_LINE('ARG_EMPID :'||ARG_EMPID);
    DBMS_OUTPUT.PUT_LINE('ARG_ENAME :'||ARG_ENAME);
    DBMS_OUTPUT.PUT_LINE('ARG_SAL :'||ARG_SAL);
    DBMS_OUTPUT.PUT_LINE('ARG_EMAIL :'||ARG_EMAIL);
END;
/
-- 바인드 변수 선언
VARIABLE VAR_ENAME VARCHAR2(30);
VARIABLE VAR_SAL VARCHAR2(30);
VARIABLE VAR_EMAIL VARCHAR2(30);
-- PROCEDURE 실행
EXEC PRO_EMPLOYEE_ARG_TEST(200, :VAR_ENAME, :VAR_SAL, :VAR_EMAIL);
-- 출력
PRINT VAR_ENAME
PRINT VAR_SAL
PRINT VAR_EMAIL
-------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PRO_ALL_EMPLOYEE
IS
BEGIN
    FOR E IN (SELECT * FROM EMPLOYEE) LOOP
        PRO_EMPLOYEE_ARG_TEST(E.EMP_ID, E.EMP_NAME, E.SALARY, E.EMAIL);
        DBMS_OUTPUT.PUT_LINE(E.EMP_ID||', '|| E.EMP_NAME||', '|| E.SALARY||', '||E.EMAIL);
    END LOOP;
END;
/
EXEC PRO_ALL_EMPLOYEE;

