-- KH JOIN 11
SELECT SUM(SALARY)
FROM EMPLOYEE;

    -- WITH 절 사용
WITH PDEPT AS
(
SELECT DEPT_CODE, SUM(SALARY) SUMSALARY
FROM EMPLOYEE E
GROUP BY DEPT_CODE
)
    -- 최종
SELECT DEPT_TITLE, SUMSALARY
FROM PDEPT P
    JOIN DEPARTMENT D ON( DEPT_ID = DEPT_CODE)
WHERE SUMSALARY > (SELECT SUM(SUMSALARY)*0.2 FROM PDEPT)
;

-- 춘대학교 02-14 (동명이인 찾기)
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2
ORDER BY STUDENT_NAME
;

-- 춘대학교 03-15 (휴학생을 뺀 평점 4.0 이상 찾기)
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", (SELECT AVG(POINT) FROM TB_GRADE WHERE STUDENT_NO=S.STUDENT_NO) 평점
FROM TB_STUDENT S
    JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
WHERE S.ABSENCE_YN = 'N'
        AND (SELECT AVG(POINT) FROM TB_GRADE where STUDENT_NO=S.STUDENT_NO) >= 4.0
ORDER BY STUDENT_NAME
;

-- 춘대학교 03-16 (환경조경학과 과목 별 평점)

SELECT CLASS_NO, CLASS_NAME, (SELECT AVG(POINT) FROM TB_GRADE WHERE CLASS_NO = C.CLASS_NO)
FROM TB_CLASS C
    JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
        AND SUBSTR(CLASS_TYPE, 1, 2) IN '전공'
ORDER BY CLASS_NAME
;
